## POST request for creating a new user

POST http://localhost:8080/user/register
Content-Type: application/json

{
  "name": "Noah Wilson",
  "username": "noah_24",
  "email": "noahwilson@example.com",
  "password": "helloNoah?",
  "gender": "Male",
  "age": "25",
  "country": "Canada",
  "address": "Toronto",
  "phoneNumber": "6543210987"
}